env:
  browser: true
  es2021: true
extends:
  - plugin:react/recommended
  - standard
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: latest
  sourceType: module
plugins:
  - react
  - '@typescript-eslint'
rules: {
  indent: ['error', 2],
  comma-dangle: ['error', {
    'objects': 'always-multiline',
    'arrays': 'always-multiline',
    'imports': 'always-multiline',
    'exports': 'always-multiline',
    'functions': 'only-multiline',
  }],
  no-unused-vars: ['warn'],
  no-undef: ['off'],
}
